name: Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */4 * * *"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up NuGet
        uses: nuget/setup-nuget@v2

      - name: Install Power Query SDK
        run: |
          nuget install Microsoft.PowerQuery.SdkTools -Version 2.127.3 -OutputDirectory ./nuget_packages

      - name: Compile Connector
        run: |
          ./nuget_packages/Microsoft.PowerQuery.SdkTools.2.127.3/tools/MakePQX.exe compile

      - name: Upload compiled extension
        uses: actions/upload-artifact@v4
        with:
          name: Arbor-PowerBI-Connector-${{ github.sha }}.mez
          path: ./bin/AnyCPU/Debug/Arbor-PowerBI-Connector.mez
